### ISSUE TITLE
No token

### ISSUE THREAD

**Issue by cokete** [YinHangCode/homebridge-mi-philips-light#21]
I've tried to extract the token trought different methods.

1- From iOS backup..... NOT WORKING
2- From miio --discover --sync ...... NOT WORKING
3- From rooted android and the file ...... APPEARS VOID..

Can someone help me?

**Comment by phenomeus** [comment]
try this "variante 1" its written in German but I think translate.google.com can help you

https://forum.smartapfel.de/forum/thread/370-xiaomi-token-auslesen/

it worked for me

**Comment by phenomeus** [comment]
Fixed here:
https://github.com/YinHangCode/homebridge-mi-philips-light/issues/19#issuecomment-373935602

**Comment by cokete** [comment]
Nothing. It doesn't work.

I've tested with iOS, with miio connected to the wifi bulb, with android.... and doesn't work.

I'm thinking is possible a change in bulb firmware. I've installed several times homebridge, but still doesn't work.

I dont know what to do now. :(

**Comment by cokete** [comment]
Can anyone help me?
